language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: staticoverride
  on:
    tags: true
    branch: master
  password:
    secure:
script:
- tox
after_success:
- coveralls
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/napalm; fi
